version: '3.8'

services:
  backend:
    image: backend:latest   # pre-build your backend image locally or push to registry
    ports:
      - "8000:8000"
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  frontend:
    image: frontend:latest  # pre-build frontend image
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
    - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: overlay
