global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s

  # Pushgateway - Batch job metrics
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 5s

  # Translation Service Backend
  - job_name: 'translation-backend'
    static_configs:
      - targets: ['backend:8000']  # Assuming your backend exposes metrics
    scrape_interval: 10s
    metrics_path: '/metrics'
    scrape_timeout: 5s

  # Docker Swarm Services Discovery
  - job_name: 'docker-swarm'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: services
        port: 8080
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: service_name
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: node_name

  # Static targets for your translation app services
  - job_name: 'translation-app'
    static_configs:
      - targets: 
        - 'translation-app_backend:8000'
        - 'translation-app_frontend:80'
    scrape_interval: 15s